//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca_del_Papa.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Biblioteca_del_Papa.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.1//EN&quot; &quot;http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///    &lt;title&gt;{ChapterTitle}&lt;/title&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;style.css&quot; /&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///    &lt;p&gt;&lt;b&gt;{ChapterTitle}&lt;/b&gt;&lt;/p&gt;
        ///    {ChapterContent}
        ///  &lt;/body&gt;
        ///&lt;/html&gt;
        /// 的本地化字符串。
        /// </summary>
        internal static string chapterTemplate {
            get {
                return ResourceManager.GetString("chapterTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;container version=&quot;1.0&quot; xmlns=&quot;urn:oasis:names:tc:opendocument:xmlns:container&quot;&gt;
        ///  &lt;rootfiles&gt;
        ///    &lt;rootfile full-path=&quot;OEBPS/content.opf&quot; media-type=&quot;application/oebps-package+xml&quot;/&gt;
        ///  &lt;/rootfiles&gt;
        ///&lt;/container&gt;
        /// 的本地化字符串。
        /// </summary>
        internal static string container {
            get {
                return ResourceManager.GetString("container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;&lt;package unique-identifier=&quot;ShuHuang&quot; xmlns=&quot;http://www.idpf.org/2007/opf&quot; version=&quot;2.0&quot;&gt;
        ///  &lt;metadata&gt;
        ///    &lt;dc-metadata xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///      &lt;meta name=&quot;cover&quot; content=&quot;cover-image&quot;/&gt;
        ///      &lt;dc:title&gt;{BookTitle}&lt;/dc:title&gt;
        ///      &lt;dc:creator&gt;{Author}&lt;/dc:creator&gt;
        ///      &lt;dc:contributor&gt;{AppName}制作，书籍版权归原作者所有&lt;/dc:contributor&gt;
        ///      &lt;dc:date&gt;{ [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string contentTemplate {
            get {
                return ResourceManager.GetString("contentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 body {
        ///font-family: sans-serif;
        ///}
        ///h1,h2,h3,h4 {
        ///font-family: serif;
        ///color: red;
        ///}
        /// 的本地化字符串。
        /// </summary>
        internal static string style {
            get {
                return ResourceManager.GetString("style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;&lt;ncx version=&quot;2005-1&quot; xmlns=&quot;http://www.daisy.org/z3986/2005/ncx/&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta name=&quot;dtb:uid&quot; content=&quot;&quot;/&gt;
        ///    &lt;meta name=&quot;dtb:depth&quot; content=&quot;-1&quot;/&gt;
        ///    &lt;meta name=&quot;dtb:totalPageCount&quot; content=&quot;0&quot;/&gt;
        ///    &lt;meta name=&quot;dtb:maxPageNumber&quot; content=&quot;0&quot;/&gt;
        ///  &lt;/head&gt;
        ///  &lt;docTitle&gt;
        ///    &lt;text&gt;{BookTitle}&lt;/text&gt;
        ///  &lt;/docTitle&gt;
        ///  &lt;docAuthor&gt;
        ///    &lt;text&gt;{Author}&lt;/text&gt;
        ///  &lt;/docAuthor&gt;
        ///  &lt;navMap&gt;
        ///    {navMap}
        ///  &lt;/navMap&gt;
        ///&lt;/ncx&gt; 的本地化字符串。
        /// </summary>
        internal static string tocTemplate {
            get {
                return ResourceManager.GetString("tocTemplate", resourceCulture);
            }
        }
    }
}
